disabled_rules:
    - identifier_name
    - trailing_comma
    - colon
    - type_body_length
    - function_body_length
    - opening_brace
    - line_length
    - file_length

cyclomatic_complexity: 12
