disabled_rules:
    - identifier_name
    - trailing_comma
    - colon
    - type_body_length
    - function_body_length
    - opening_brace
    - line_length
    - file_length
    - inclusive_language # This rule is broken. 'Master' is used within the TLS specification itself, I can't change that.
excluded:
    - 'AppDelegate.swift'
    - 'SceneDelegate.swift'
    - 'External/'
